// Package testkit builds the fakes this project's tests run against: a Codex CLI
// that is a bash script, an in-memory Telegram, and a workspace that looks like a
// Git repository.
//
// Nothing here touches the network, a real bot token, or a real Codex account.
// The fake Codex records the exact argv, cwd and environment of every
// invocation, which is what lets the tests assert on the real command line
// instead of on a reconstruction of it.
package testkit

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"codex-telegram-bot/internal/telegram"
)

// Workspace returns a temporary directory that passes the bot's "must be a Git
// repository" check.
//
// It creates a bare .git directory rather than running `git init`, so the tests
// do not depend on git being installed or on its configuration.
func Workspace(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".git"), 0o755); err != nil {
		t.Fatalf("create a fake .git: %v", err)
	}
	return dir
}

// StateDir returns an empty temporary directory for BOT_STATE_DIR.
func StateDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.Chmod(dir, 0o700); err != nil {
		t.Fatalf("chmod state dir: %v", err)
	}
	return dir
}

// CodexHome returns an empty temporary directory for CODEX_HOME.
func CodexHome(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.Chmod(dir, 0o700); err != nil {
		t.Fatalf("chmod codex home: %v", err)
	}
	return dir
}

// --- fake codex ------------------------------------------------------------

// CodexSpec describes how the fake Codex CLI should behave.
type CodexSpec struct {
	// Stdout is written to stdout verbatim. Use Events to build a valid JSONL
	// stream.
	Stdout string
	// Stderr is written to stderr verbatim.
	Stderr string
	// Exit is the exit status.
	Exit int
	// SleepBefore delays any output, for cancellation and timeout tests.
	SleepBefore time.Duration
	// SpawnChild starts a background `sleep 600` in the same process group and
	// records its pid, so a test can assert that killing the group reached the
	// grandchild and not just the direct child.
	SpawnChild bool
	// AppendStdout is written to stdout *after* the sleep, so a test can model a
	// turn that reports thread.started immediately and only produces its final
	// answer much later — which is what the real CLI does, and what makes a
	// cancellation test able to observe a thread id.
	AppendStdout string
	// ResumeStdout replaces Stdout when the invocation is a resume, that is when
	// "resume" appears in argv. It lets a test give the first turn and the
	// resumed turn different answers, which is how it can tell them apart.
	ResumeStdout string
}

// FakeCodex is a running-record of a fake Codex CLI.
type FakeCodex struct {
	// Path is the executable to point BOT_CODEX_BIN at.
	Path string
	// ArtifactDir holds one argv.<n>, cwd.<n> and env.<n> file per invocation.
	ArtifactDir string
}

// NewFakeCodex writes the fake and registers cleanup.
func NewFakeCodex(t *testing.T, spec CodexSpec) *FakeCodex {
	t.Helper()
	dir := t.TempDir()
	artifacts := filepath.Join(dir, "artifacts")
	if err := os.MkdirAll(artifacts, 0o700); err != nil {
		t.Fatalf("create artifact dir: %v", err)
	}

	// Payloads live in their own files so nothing has to be escaped into the
	// script body: a prompt with quotes, newlines or shell metacharacters is
	// exactly what these tests must handle.
	write := func(name, content string) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
		return p
	}
	stdoutPath := write("stdout.txt", spec.Stdout)
	stdout2Path := write("stdout2.txt", spec.AppendStdout)
	stderrPath := write("stderr.txt", spec.Stderr)
	resumePath := write("resume.txt", spec.ResumeStdout)

	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Fake codex CLI generated by internal/testkit. Records each invocation.\n")
	sb.WriteString("set -u\n")
	fmt.Fprintf(&sb, "ART=%s\n", shQuote(artifacts))
	sb.WriteString(`mkdir -p "$ART"
n=$(cat "$ART/count" 2>/dev/null || echo 0)
n=$((n+1))
printf '%s' "$n" > "$ART/count"
: > "$ART/argv.$n"
for a in "$@"; do printf '%s\0' "$a" >> "$ART/argv.$n"; done
printf '%s' "$PWD" > "$ART/cwd.$n"
env | LC_ALL=C sort > "$ART/env.$n"
# Record stdin. If the caller left a pipe open instead of /dev/null this blocks
# forever, which is exactly what the "stdin must be closed" test wants to catch.
cat > "$ART/stdin.$n"
# Record when this invocation started and ended, so a test can prove that two
# turns sharing a working tree never overlapped.
printf 'start %s %s\n' "$n" "$(date +%s.%N)" >> "$ART/timeline"
`)
	fmt.Fprintf(&sb, "[ -s %s ] && cat %s >&2\n", shQuote(stderrPath), shQuote(stderrPath))
	// Stdout comes first: the real CLI streams thread.started as soon as the
	// thread exists, long before the turn finishes.
	if spec.ResumeStdout == "" {
		fmt.Fprintf(&sb, "[ -s %s ] && cat %s\n", shQuote(stdoutPath), shQuote(stdoutPath))
	} else {
		fmt.Fprintf(&sb, "case \" $* \" in *\" resume \"*) PAYLOAD=%s ;; *) PAYLOAD=%s ;; esac\n",
			shQuote(resumePath), shQuote(stdoutPath))
		fmt.Fprintf(&sb, "[ -s \"$PAYLOAD\" ] && cat \"$PAYLOAD\"\n")
	}
	sb.WriteString(`printf 'x' > "$ART/emitted.$n"
`)
	if spec.SpawnChild {
		sb.WriteString(`sleep 600 &
printf '%s' "$!" > "$ART/child.$n"
`)
	}
	if spec.SleepBefore > 0 {
		fmt.Fprintf(&sb, "sleep %s\n", strconv.FormatFloat(spec.SleepBefore.Seconds(), 'f', 3, 64))
	}
	fmt.Fprintf(&sb, "[ -s %s ] && cat %s\n", shQuote(stdout2Path), shQuote(stdout2Path))
	sb.WriteString(`printf 'end %s %s\n' "$n" "$(date +%s.%N)" >> "$ART/timeline"
`)
	fmt.Fprintf(&sb, "exit %d\n", spec.Exit)

	bin := filepath.Join(dir, "codex")
	if err := os.WriteFile(bin, []byte(sb.String()), 0o700); err != nil {
		t.Fatalf("write fake codex: %v", err)
	}
	return &FakeCodex{Path: bin, ArtifactDir: artifacts}
}

// Invocations returns every recorded argv, oldest first.
func (f *FakeCodex) Invocations(t *testing.T) [][]string {
	t.Helper()
	n := f.count(t)
	out := make([][]string, 0, n)
	for i := 1; i <= n; i++ {
		out = append(out, f.Argv(t, i))
	}
	return out
}

// Argv returns the argv of invocation n (1-based).
func (f *FakeCodex) Argv(t *testing.T, n int) []string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, fmt.Sprintf("argv.%d", n)))
	if err != nil {
		t.Fatalf("read argv.%d: %v", n, err)
	}
	s := string(raw)
	if s == "" {
		return nil
	}
	parts := strings.Split(s, "\x00")
	// A trailing NUL produces one empty element.
	if len(parts) > 0 && parts[len(parts)-1] == "" {
		parts = parts[:len(parts)-1]
	}
	return parts
}

// CWD returns the working directory of invocation n.
func (f *FakeCodex) CWD(t *testing.T, n int) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, fmt.Sprintf("cwd.%d", n)))
	if err != nil {
		t.Fatalf("read cwd.%d: %v", n, err)
	}
	return string(raw)
}

// Env returns the environment of invocation n as a map.
func (f *FakeCodex) Env(t *testing.T, n int) map[string]string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, fmt.Sprintf("env.%d", n)))
	if err != nil {
		t.Fatalf("read env.%d: %v", n, err)
	}
	m := make(map[string]string)
	for _, line := range strings.Split(string(raw), "\n") {
		k, v, ok := strings.Cut(line, "=")
		if ok {
			m[k] = v
		}
	}
	return m
}

// Interval is one fake-Codex invocation's lifetime, as recorded in the timeline.
type Interval struct {
	N     int
	Start time.Time
	End   time.Time
}

// Timeline returns every recorded invocation interval, oldest first.
func (f *FakeCodex) Timeline(t *testing.T) []Interval {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, "timeline"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		t.Fatalf("read timeline: %v", err)
	}
	starts := map[int]time.Time{}
	var out []Interval
	for _, line := range strings.Split(string(raw), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 3 {
			continue
		}
		n, err := strconv.Atoi(fields[1])
		if err != nil {
			t.Fatalf("timeline entry %q has no invocation number: %v", line, err)
		}
		at, err := timeFromEpoch(fields[2])
		if err != nil {
			t.Fatalf("timeline entry %q has no usable timestamp: %v", line, err)
		}
		switch fields[0] {
		case "start":
			starts[n] = at
		case "end":
			start, ok := starts[n]
			if !ok {
				continue
			}
			out = append(out, Interval{N: n, Start: start, End: at})
		}
	}
	// An invocation that was killed never writes its "end" line, so it has no
	// measurable interval. Callers that care about a killed turn check the
	// invocation count instead.
	return out
}

// Overlaps reports whether any two intervals ran at the same time.
func Overlaps(in []Interval) (Interval, Interval, bool) {
	for i := 0; i < len(in); i++ {
		for j := i + 1; j < len(in); j++ {
			a, b := in[i], in[j]
			if a.Start.Before(b.End) && b.Start.Before(a.End) {
				return a, b, true
			}
		}
	}
	return Interval{}, Interval{}, false
}

// timeFromEpoch parses the "seconds.nanoseconds" form date +%s.%N prints.
func timeFromEpoch(s string) (time.Time, error) {
	sec, frac, found := strings.Cut(s, ".")
	whole, err := strconv.ParseInt(sec, 10, 64)
	if err != nil {
		return time.Time{}, err
	}
	var nanos int64
	if found {
		// Pad or trim to exactly nine digits.
		frac = (frac + "000000000")[:9]
		nanos, err = strconv.ParseInt(frac, 10, 64)
		if err != nil {
			return time.Time{}, err
		}
	}
	return time.Unix(whole, nanos), nil
}

// WaitForEmitted blocks until invocation n has written its early stdout — the
// thread.started line a real Codex emits before it does any work.
//
// A cancellation test needs this. Without it, /stop can land before the child has
// printed anything, and "the session kept its thread id" would be asserting
// something that never had a chance to happen.
func (f *FakeCodex) WaitForEmitted(t *testing.T, n int, within time.Duration) {
	t.Helper()
	path := filepath.Join(f.ArtifactDir, fmt.Sprintf("emitted.%d", n))
	deadline := time.Now().Add(within)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(path); err == nil {
			// The bytes are in the pipe by now; give the reader a moment to
			// consume them. It is blocked in a read that returns as soon as
			// data is available, so this margin is generous rather than tight.
			time.Sleep(250 * time.Millisecond)
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatalf("invocation %d never wrote its early output", n)
}

// Stdin returns whatever invocation n read from stdin.
//
// The runner passes no stdin, so Go gives the child /dev/null and this is empty.
// A non-empty answer means caller-controlled bytes reached the child through a
// channel other than argv.
func (f *FakeCodex) Stdin(t *testing.T, n int) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, fmt.Sprintf("stdin.%d", n)))
	if err != nil {
		t.Fatalf("read stdin.%d: %v", n, err)
	}
	return string(raw)
}

// ChildPID returns the pid of the background process invocation n spawned, or 0.
func (f *FakeCodex) ChildPID(t *testing.T, n int) int {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, fmt.Sprintf("child.%d", n)))
	if err != nil {
		if os.IsNotExist(err) {
			return 0
		}
		t.Fatalf("read child.%d: %v", n, err)
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(raw)))
	if err != nil {
		t.Fatalf("child.%d is not a pid: %v", n, err)
	}
	return pid
}

func (f *FakeCodex) count(t *testing.T) int {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.ArtifactDir, "count"))
	if err != nil {
		if os.IsNotExist(err) {
			return 0
		}
		t.Fatalf("read count: %v", err)
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(raw)))
	if err != nil {
		t.Fatalf("count is not a number: %v", err)
	}
	return n
}

// Alive reports whether a pid still exists.
//
// Signal 0 delivers nothing and only checks existence, which is exactly the
// question a process-group test needs to answer.
func Alive(pid int) bool {
	if pid <= 0 {
		return false
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	return proc.Signal(syscall.Signal(0)) == nil
}

// --- JSONL builders --------------------------------------------------------

// Events builds the JSONL stream Codex produces for a successful turn, matching
// the shape published in the Codex non-interactive-mode documentation and
// observed from codex-cli 0.156.1.
func Events(threadID, reply string) string {
	return strings.Join([]string{
		`{"type":"thread.started","thread_id":` + jsonQuote(threadID) + `}`,
		`{"type":"turn.started"}`,
		`{"type":"item.started","item":{"id":"item_1","type":"command_execution","command":"ls","status":"in_progress"}}`,
		`{"type":"item.completed","item":{"id":"item_1","type":"command_execution","output":"README.md","status":"completed"}}`,
		`{"type":"item.completed","item":{"id":"item_2","type":"agent_message","text":` + jsonQuote(reply) + `}}`,
		`{"type":"turn.completed","usage":{"input_tokens":100,"cached_input_tokens":80,"output_tokens":20,"reasoning_output_tokens":0}}`,
	}, "\n") + "\n"
}

// Lines joins raw JSONL lines.
func Lines(lines ...string) string { return strings.Join(lines, "\n") + "\n" }

// UUID is a syntactically valid thread id for tests.
func UUID(seed int) string {
	return fmt.Sprintf("0199a213-81c0-7800-8aa1-%012d", seed)
}

func jsonQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// shQuote wraps s in single quotes for a shell script body.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// --- fake telegram ---------------------------------------------------------

// Sent is one message the bot delivered.
type Sent struct {
	ChatID   int64
	ThreadID int64
	Text     string
	Document string
	Data     []byte
}

// FakeTelegram is an in-memory Bot API.
//
// It records everything sent and hands out a scripted queue of updates, so a
// test can assert on the exact messages a user would have seen without a token,
// a network, or a chat.
type FakeTelegram struct {
	mu       sync.Mutex
	sent     []Sent
	actions  []string
	updates  []telegram.Update
	files    map[string][]byte
	nextID   int64
	me       telegram.User
	webhook  telegram.WebhookInfo
	sendErr  error
	pollErr  error
	pollWait chan struct{}
}

// NewFakeTelegram builds a fake with a default bot identity.
func NewFakeTelegram() *FakeTelegram {
	return &FakeTelegram{
		nextID:  1000,
		files:   make(map[string][]byte),
		me:      telegram.User{ID: 42, FirstName: "Codex", Username: "codex_test_bot"},
		webhook: telegram.WebhookInfo{URL: "https://example.invalid/hook", PendingUpdateCount: 3},
	}
}

// SetFile makes a Telegram file id downloadable by the fake.
func (f *FakeTelegram) SetFile(id string, data []byte) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.files[id] = append([]byte(nil), data...)
}

func (f *FakeTelegram) DownloadFile(_ context.Context, fileID string) ([]byte, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	data, ok := f.files[fileID]
	if !ok {
		return nil, fmt.Errorf("fake Telegram: unknown file %q", fileID)
	}
	return append([]byte(nil), data...), nil
}

// Username is the bot username the fake reports from getMe.
func (f *FakeTelegram) Username() string { return f.me.Username }

// SetSendError makes every sendMessage fail with err.
func (f *FakeTelegram) SetSendError(err error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.sendErr = err
}

// SetPollError makes every getUpdates fail with err.
func (f *FakeTelegram) SetPollError(err error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.pollErr = err
}

// QueueUpdates appends updates to be returned by the next getUpdates calls.
func (f *FakeTelegram) QueueUpdates(u ...telegram.Update) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.updates = append(f.updates, u...)
}

// Sent returns every message delivered so far, in order.
func (f *FakeTelegram) Sent() []Sent {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]Sent, len(f.sent))
	copy(out, f.sent)
	return out
}

// LastText returns the text of the most recent message, or "" when none was sent.
func (f *FakeTelegram) LastText() string {
	f.mu.Lock()
	defer f.mu.Unlock()
	if len(f.sent) == 0 {
		return ""
	}
	return f.sent[len(f.sent)-1].Text
}

// AllText joins every delivered message with a newline, which is what a test
// asserting on a split reply wants.
func (f *FakeTelegram) AllText() string {
	f.mu.Lock()
	defer f.mu.Unlock()
	parts := make([]string, 0, len(f.sent))
	for _, s := range f.sent {
		parts = append(parts, s.Text)
	}
	return strings.Join(parts, "\n")
}

// Actions returns the chat actions requested, e.g. "typing".
func (f *FakeTelegram) Actions() []string {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]string, len(f.actions))
	copy(out, f.actions)
	return out
}

// Reset clears the recorded messages.
func (f *FakeTelegram) Reset() {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.sent = nil
	f.actions = nil
}

// SendMessage records a message.
func (f *FakeTelegram) SendMessage(_ context.Context, chatID, threadID int64, text string) (*telegram.SentMessage, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.sendErr != nil {
		return nil, f.sendErr
	}
	f.nextID++
	f.sent = append(f.sent, Sent{ChatID: chatID, ThreadID: threadID, Text: text})
	return &telegram.SentMessage{MessageID: f.nextID}, nil
}

func (f *FakeTelegram) SendDocument(_ context.Context, chatID, threadID int64, path string) (*telegram.SentMessage, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.sendErr != nil {
		return nil, f.sendErr
	}
	f.nextID++
	f.sent = append(f.sent, Sent{ChatID: chatID, ThreadID: threadID, Document: filepath.Base(path), Data: data})
	return &telegram.SentMessage{MessageID: f.nextID}, nil
}

// SendChatAction records a typing indicator.
func (f *FakeTelegram) SendChatAction(_ context.Context, _, _ int64, action string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.actions = append(f.actions, action)
	return nil
}

// GetMe returns the fake bot identity.
func (f *FakeTelegram) GetMe(context.Context) (*telegram.User, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	u := f.me
	return &u, nil
}

// GetWebhookInfo returns a webhook so the deletion path is exercised.
func (f *FakeTelegram) GetWebhookInfo(context.Context) (*telegram.WebhookInfo, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	w := f.webhook
	return &w, nil
}

// DeleteWebhook clears the fake webhook.
func (f *FakeTelegram) DeleteWebhook(context.Context, bool) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.webhook = telegram.WebhookInfo{}
	return nil
}

// GetUpdates returns up to limit queued updates and advances nothing else.
func (f *FakeTelegram) GetUpdates(ctx context.Context, offset int64, _ time.Duration, limit int) ([]telegram.Update, error) {
	f.mu.Lock()
	pollErr := f.pollErr
	var out []telegram.Update
	keep := f.updates[:0]
	for _, u := range f.updates {
		if u.UpdateID >= offset && len(out) < limit {
			out = append(out, u)
			continue
		}
		keep = append(keep, u)
	}
	f.updates = keep
	f.mu.Unlock()

	if pollErr != nil {
		return nil, pollErr
	}
	return out, nil
}

// --- update builders -------------------------------------------------------

// MessageUpdate builds a private-chat text message update.
func MessageUpdate(updateID, chatID, userID int64, text string) telegram.Update {
	return telegram.Update{
		UpdateID: updateID,
		Message: &telegram.Message{
			MessageID: updateID,
			Date:      time.Now().Unix(),
			Text:      text,
			From:      &telegram.User{ID: userID, FirstName: "User"},
			Chat:      telegram.Chat{ID: chatID, Type: "private"},
		},
	}
}

// TopicUpdate builds a private-chat text message inside a topic.
func TopicUpdate(updateID, chatID, threadID, userID int64, text string) telegram.Update {
	u := MessageUpdate(updateID, chatID, userID, text)
	u.Message.MessageThreadID = threadID
	return u
}

// GroupUpdate builds a supergroup message update.
func GroupUpdate(updateID, chatID, userID int64, text string) telegram.Update {
	u := MessageUpdate(updateID, chatID, userID, text)
	u.Message.Chat.Type = "supergroup"
	return u
}
